package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// OperationMutator is used to build an instance of Operation. The user must
// call `Do()` after providing all the necessary information to
// the new instance of Operation with new values
type OperationMutator struct {
	proxy  *operation
	target *operation
}

// Do finalizes the matuation process for Operation and returns the result
func (b *OperationMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateOperation creates a new mutator object for Operation
func MutateOperation(v Operation) *OperationMutator {
	return &OperationMutator{
		target: v.(*operation),
		proxy:  v.Clone().(*operation),
	}
}

func (m *OperationMutator) ClearTags() *OperationMutator {
	m.proxy.tags.Clear()
	return m
}

func (m *OperationMutator) Tag(value string) *OperationMutator {
	m.proxy.tags = append(m.proxy.tags, value)
	return m
}

// Summary sets the Summary field for object Operation.
func (m *OperationMutator) Summary(v string) *OperationMutator {
	m.proxy.summary = v
	return m
}

// Description sets the Description field for object Operation.
func (m *OperationMutator) Description(v string) *OperationMutator {
	m.proxy.description = v
	return m
}

// ExternalDocs sets the ExternalDocs field for object Operation.
func (m *OperationMutator) ExternalDocs(v ExternalDocumentation) *OperationMutator {
	m.proxy.externalDocs = v
	return m
}

// OperationID sets the OperationID field for object Operation.
func (m *OperationMutator) OperationID(v string) *OperationMutator {
	m.proxy.operationID = v
	return m
}

func (m *OperationMutator) ClearConsumes() *OperationMutator {
	m.proxy.consumes.Clear()
	return m
}

func (m *OperationMutator) Consume(value string) *OperationMutator {
	m.proxy.consumes = append(m.proxy.consumes, value)
	return m
}

func (m *OperationMutator) ClearProduces() *OperationMutator {
	m.proxy.produces.Clear()
	return m
}

func (m *OperationMutator) Produce(value string) *OperationMutator {
	m.proxy.produces = append(m.proxy.produces, value)
	return m
}

func (m *OperationMutator) ClearParameters() *OperationMutator {
	m.proxy.parameters.Clear()
	return m
}

func (m *OperationMutator) Parameter(value Parameter) *OperationMutator {
	m.proxy.parameters = append(m.proxy.parameters, value)
	return m
}

// Responses sets the Responses field for object Operation.
func (m *OperationMutator) Responses(v Responses) *OperationMutator {
	m.proxy.responses = v
	return m
}

func (m *OperationMutator) ClearSchemes() *OperationMutator {
	m.proxy.schemes.Clear()
	return m
}

func (m *OperationMutator) Scheme(value string) *OperationMutator {
	m.proxy.schemes = append(m.proxy.schemes, value)
	return m
}

// Deprecated sets the Deprecated field for object Operation.
func (m *OperationMutator) Deprecated(v bool) *OperationMutator {
	m.proxy.deprecated = v
	return m
}

func (m *OperationMutator) ClearSecurity() *OperationMutator {
	m.proxy.security.Clear()
	return m
}

func (m *OperationMutator) Security(value SecurityRequirement) *OperationMutator {
	m.proxy.security = append(m.proxy.security, value)
	return m
}
func (b *OperationMutator) Extension(name string, value interface{}) *OperationMutator {
	if b.proxy.extensions == nil {
		b.proxy.extensions = Extensions{}
	}
	b.proxy.extensions[name] = value
	return b
}
