package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// ParameterMutator is used to build an instance of Parameter. The user must
// call `Do()` after providing all the necessary information to
// the new instance of Parameter with new values
type ParameterMutator struct {
	proxy  *parameter
	target *parameter
}

// Do finalizes the matuation process for Parameter and returns the result
func (b *ParameterMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateParameter creates a new mutator object for Parameter
func MutateParameter(v Parameter) *ParameterMutator {
	return &ParameterMutator{
		target: v.(*parameter),
		proxy:  v.Clone().(*parameter),
	}
}

// Name sets the Name field for object Parameter.
func (m *ParameterMutator) Name(v string) *ParameterMutator {
	m.proxy.name = v
	return m
}

// Description sets the Description field for object Parameter.
func (m *ParameterMutator) Description(v string) *ParameterMutator {
	m.proxy.description = v
	return m
}

// Required sets the Required field for object Parameter.
func (m *ParameterMutator) Required(v bool) *ParameterMutator {
	m.proxy.required = v
	return m
}

// In sets the In field for object Parameter.
func (m *ParameterMutator) In(v Location) *ParameterMutator {
	m.proxy.in = v
	return m
}

// Schema sets the Schema field for object Parameter.
func (m *ParameterMutator) Schema(v Schema) *ParameterMutator {
	m.proxy.schema = v
	return m
}

// Type sets the Type field for object Parameter.
func (m *ParameterMutator) Type(v PrimitiveType) *ParameterMutator {
	m.proxy.typ = v
	return m
}

// Format sets the Format field for object Parameter.
func (m *ParameterMutator) Format(v string) *ParameterMutator {
	m.proxy.format = v
	return m
}

// Title sets the Title field for object Parameter.
func (m *ParameterMutator) Title(v string) *ParameterMutator {
	m.proxy.title = v
	return m
}

// AllowEmptyValue sets the AllowEmptyValue field for object Parameter.
func (m *ParameterMutator) AllowEmptyValue(v bool) *ParameterMutator {
	m.proxy.allowEmptyValue = v
	return m
}

// Items sets the Items field for object Parameter.
func (m *ParameterMutator) Items(v Items) *ParameterMutator {
	m.proxy.items = v
	return m
}

// CollectionFormat sets the CollectionFormat field for object Parameter.
func (m *ParameterMutator) CollectionFormat(v CollectionFormat) *ParameterMutator {
	m.proxy.collectionFormat = v
	return m
}

// DefaultValue sets the DefaultValue field for object Parameter.
func (m *ParameterMutator) DefaultValue(v interface{}) *ParameterMutator {
	m.proxy.defaultValue = v
	return m
}

// ClearMaximum clears the maximum field
func (m *ParameterMutator) ClearMaximum() *ParameterMutator {
	m.proxy.maximum = nil
	return m
}

// Maximum sets the maximum field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) Maximum(v float64) *ParameterMutator {
	m.proxy.maximum = &v
	return m
}

// ClearExclusiveMaximum clears the exclusiveMaximum field
func (m *ParameterMutator) ClearExclusiveMaximum() *ParameterMutator {
	m.proxy.exclusiveMaximum = nil
	return m
}

// ExclusiveMaximum sets the exclusiveMaximum field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) ExclusiveMaximum(v float64) *ParameterMutator {
	m.proxy.exclusiveMaximum = &v
	return m
}

// ClearMinimum clears the minimum field
func (m *ParameterMutator) ClearMinimum() *ParameterMutator {
	m.proxy.minimum = nil
	return m
}

// Minimum sets the minimum field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) Minimum(v float64) *ParameterMutator {
	m.proxy.minimum = &v
	return m
}

// ClearExclusiveMinimum clears the exclusiveMinimum field
func (m *ParameterMutator) ClearExclusiveMinimum() *ParameterMutator {
	m.proxy.exclusiveMinimum = nil
	return m
}

// ExclusiveMinimum sets the exclusiveMinimum field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) ExclusiveMinimum(v float64) *ParameterMutator {
	m.proxy.exclusiveMinimum = &v
	return m
}

// ClearMaxLength clears the maxLength field
func (m *ParameterMutator) ClearMaxLength() *ParameterMutator {
	m.proxy.maxLength = nil
	return m
}

// MaxLength sets the maxLength field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) MaxLength(v int) *ParameterMutator {
	m.proxy.maxLength = &v
	return m
}

// ClearMinLength clears the minLength field
func (m *ParameterMutator) ClearMinLength() *ParameterMutator {
	m.proxy.minLength = nil
	return m
}

// MinLength sets the minLength field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) MinLength(v int) *ParameterMutator {
	m.proxy.minLength = &v
	return m
}

// Pattern sets the Pattern field for object Parameter.
func (m *ParameterMutator) Pattern(v string) *ParameterMutator {
	m.proxy.pattern = v
	return m
}

// ClearMaxItems clears the maxItems field
func (m *ParameterMutator) ClearMaxItems() *ParameterMutator {
	m.proxy.maxItems = nil
	return m
}

// MaxItems sets the maxItems field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) MaxItems(v int) *ParameterMutator {
	m.proxy.maxItems = &v
	return m
}

// ClearMinItems clears the minItems field
func (m *ParameterMutator) ClearMinItems() *ParameterMutator {
	m.proxy.minItems = nil
	return m
}

// MinItems sets the minItems field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) MinItems(v int) *ParameterMutator {
	m.proxy.minItems = &v
	return m
}

// UniqueItems sets the UniqueItems field for object Parameter.
func (m *ParameterMutator) UniqueItems(v bool) *ParameterMutator {
	m.proxy.uniqueItems = v
	return m
}

func (m *ParameterMutator) ClearEnum() *ParameterMutator {
	m.proxy.enum.Clear()
	return m
}

func (m *ParameterMutator) Enum(value interface{}) *ParameterMutator {
	m.proxy.enum = append(m.proxy.enum, value)
	return m
}

// ClearMultipleOf clears the multipleOf field
func (m *ParameterMutator) ClearMultipleOf() *ParameterMutator {
	m.proxy.multipleOf = nil
	return m
}

// MultipleOf sets the multipleOf field.%!(EXTRA string=Parameter)
func (m *ParameterMutator) MultipleOf(v float64) *ParameterMutator {
	m.proxy.multipleOf = &v
	return m
}
func (b *ParameterMutator) Extension(name string, value interface{}) *ParameterMutator {
	if b.proxy.extensions == nil {
		b.proxy.extensions = Extensions{}
	}
	b.proxy.extensions[name] = value
	return b
}
