package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"github.com/pkg/errors"
	"sync"
)

var _ = errors.Cause

// PathsBuilder is used to build an instance of Paths. The user must
// call `Build()` after providing all the necessary information to
// build an instance of Paths.
// Builders may NOT be reused. It must be created for every instance
// of Paths that you want to create
type PathsBuilder struct {
	mu     sync.Mutex
	target *paths
}

// MustBuild is a convenience function for those time when you know that
// the result of the builder must be successful
func (b *PathsBuilder) MustBuild(options ...Option) Paths {
	v, err := b.Build(options...)
	if err != nil {
		panic(err)
	}
	return v
}

// Build finalizes the building process for Paths and returns the result
// By default, Build() will validate if the given structure is valid
func (b *PathsBuilder) Build(options ...Option) (Paths, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.target == nil {
		return nil, errors.New(`builder has already been used`)
	}
	validate := true
	for _, option := range options {
		switch option.Name() {
		case optkeyValidate:
			validate = option.Value().(bool)
		}
	}
	if validate {
		if err := b.target.Validate(false); err != nil {
			return nil, errors.Wrap(err, `validation failed`)
		}
	}
	defer func() { b.target = nil }()
	return b.target, nil
}

// NewPaths creates a new builder object for Paths
func NewPaths() *PathsBuilder {
	var b PathsBuilder
	b.target = &paths{}
	return &b
}

// Paths sets the paths field for object Paths.

func (b *PathsBuilder) Paths(v PathItemMap) *PathsBuilder {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.target == nil {
		return b
	}
	b.target.paths = v
	return b
}

// Reference sets the $ref (reference) field for object Paths.
func (b *PathsBuilder) Reference(v string) *PathsBuilder {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.target == nil {
		return b
	}
	b.target.reference = v
	return b
}

// Extension sets an arbitrary element (an extension) to the
// object Paths. The extension name should start with a "x-"
func (b *PathsBuilder) Extension(name string, value interface{}) *PathsBuilder {
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.target == nil {
		return b
	}
	b.target.extensions[name] = value
	return b
}
