package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// ResponsesMutator is used to build an instance of Responses. The user must
// call `Do()` after providing all the necessary information to
// the new instance of Responses with new values
type ResponsesMutator struct {
	proxy  *responses
	target *responses
}

// Do finalizes the matuation process for Responses and returns the result
func (b *ResponsesMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateResponses creates a new mutator object for Responses
func MutateResponses(v Responses) *ResponsesMutator {
	return &ResponsesMutator{
		target: v.(*responses),
		proxy:  v.Clone().(*responses),
	}
}

// DefaultValue sets the DefaultValue field for object Responses.
func (b *ResponsesMutator) DefaultValue(v Response) *ResponsesMutator {
	b.proxy.defaultValue = v
	return b
}
func (b *ResponsesMutator) Extension(name string, value interface{}) *ResponsesMutator {
	if b.proxy.extensions == nil {
		b.proxy.extensions = Extensions{}
	}
	b.proxy.extensions[name] = value
	return b
}
