package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// ResponseMutator is used to build an instance of Response. The user must
// call `Do()` after providing all the necessary information to
// the new instance of Response with new values
type ResponseMutator struct {
	proxy  *response
	target *response
}

// Do finalizes the matuation process for Response and returns the result
func (b *ResponseMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateResponse creates a new mutator object for Response
func MutateResponse(v Response) *ResponseMutator {
	return &ResponseMutator{
		target: v.(*response),
		proxy:  v.Clone().(*response),
	}
}

// Name sets the Name field for object Response.
func (m *ResponseMutator) Name(v string) *ResponseMutator {
	m.proxy.name = v
	return m
}

// StatusCode sets the StatusCode field for object Response.
func (m *ResponseMutator) StatusCode(v string) *ResponseMutator {
	m.proxy.statusCode = v
	return m
}

// Description sets the Description field for object Response.
func (m *ResponseMutator) Description(v string) *ResponseMutator {
	m.proxy.description = v
	return m
}

// Schema sets the Schema field for object Response.
func (m *ResponseMutator) Schema(v Schema) *ResponseMutator {
	m.proxy.schema = v
	return m
}

func (m *ResponseMutator) ClearHeaders() *ResponseMutator {
	m.proxy.headers.Clear()
	return m
}

func (m *ResponseMutator) Header(key HeaderMapKey, value Header) *ResponseMutator {
	if m.proxy.headers == nil {
		m.proxy.headers = HeaderMap{}
	}

	m.proxy.headers[key] = value
	return m
}

func (m *ResponseMutator) ClearExamples() *ResponseMutator {
	m.proxy.examples.Clear()
	return m
}

func (m *ResponseMutator) Example(key ExampleMapKey, value interface{}) *ResponseMutator {
	if m.proxy.examples == nil {
		m.proxy.examples = ExampleMap{}
	}

	m.proxy.examples[key] = value
	return m
}
func (b *ResponseMutator) Extension(name string, value interface{}) *ResponseMutator {
	if b.proxy.extensions == nil {
		b.proxy.extensions = Extensions{}
	}
	b.proxy.extensions[name] = value
	return b
}
