package openapi

// This file was automatically generated by gentyeps.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// SecurityRequirementMutator is used to build an instance of SecurityRequirement. The user must
// call `Do()` after providing all the necessary information to
// the new instance of SecurityRequirement with new values
type SecurityRequirementMutator struct {
	proxy  *securityRequirement
	target *securityRequirement
}

// Do finalizes the matuation process for SecurityRequirement and returns the result
func (b *SecurityRequirementMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateSecurityRequirement creates a new mutator object for SecurityRequirement
func MutateSecurityRequirement(v SecurityRequirement) *SecurityRequirementMutator {
	return &SecurityRequirementMutator{
		target: v.(*securityRequirement),
		proxy:  v.Clone().(*securityRequirement),
	}
}

// Data sets the Data field for object SecurityRequirement.
func (b *SecurityRequirementMutator) Data(v map[string][]string) *SecurityRequirementMutator {
	b.proxy.data = v
	return b
}
func (b *SecurityRequirementMutator) Extension(name string, value interface{}) *SecurityRequirementMutator {
	if b.proxy.extensions == nil {
		b.proxy.extensions = Extensions{}
	}
	b.proxy.extensions[name] = value
	return b
}
