package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// SecurityRequirementMutator is used to build an instance of SecurityRequirement. The user must
// call `Do()` after providing all the necessary information to
// the new instance of SecurityRequirement with new values
type SecurityRequirementMutator struct {
	proxy  *securityRequirement
	target *securityRequirement
}

// Do finalizes the matuation process for SecurityRequirement and returns the result
func (m *SecurityRequirementMutator) Do() error {
	*m.target = *m.proxy
	return nil
}

// MutateSecurityRequirement creates a new mutator object for SecurityRequirement
func MutateSecurityRequirement(v SecurityRequirement) *SecurityRequirementMutator {
	return &SecurityRequirementMutator{
		target: v.(*securityRequirement),
		proxy:  v.Clone().(*securityRequirement),
	}
}

// Data sets the Data field for object SecurityRequirement.
func (m *SecurityRequirementMutator) Data(v map[string][]string) *SecurityRequirementMutator {
	m.proxy.data = v
	return m
}

// Extension sets an arbitrary extension field in SecurityRequirement
func (m *SecurityRequirementMutator) Extension(name string, value interface{}) *SecurityRequirementMutator {
	if m.proxy.extensions == nil {
		m.proxy.extensions = Extensions{}
	}
	m.proxy.extensions[name] = value
	return m
}
