package openapi

// This file was automatically generated by gentyeps.go on 2018-05-28T21:36:31+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"fmt"
	"github.com/pkg/errors"
	"log"
	"strconv"
	"strings"
)

var _ = json.Unmarshal
var _ = log.Printf
var _ = errors.Cause

type xmlMarshalProxy struct {
	Reference string `json:"$ref,omitempty"`
	Name      string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Prefix    string `json:"prefix,omitempty"`
	Attribute bool   `json:"attribute,omitempty"`
	Wrapped   bool   `json:"wrapped,omitempty"`
}

func (v *xml) MarshalJSON() ([]byte, error) {
	var proxy xmlMarshalProxy
	if s := v.reference; len(s) > 0 {
		return []byte(fmt.Sprintf(refOnlyTmpl, strconv.Quote(s))), nil
	}
	proxy.Name = v.name
	proxy.Namespace = v.namespace
	proxy.Prefix = v.prefix
	proxy.Attribute = v.attribute
	proxy.Wrapped = v.wrapped
	buf, err := json.Marshal(proxy)
	if err != nil {
		return nil, errors.Wrap(err, `failed to marshal struct`)
	}
	if len(v.extras) > 0 {
		extrasBuf, err := json.Marshal(v.extras)
		if err != nil || len(extrasBuf) <= 2 {
			return nil, errors.Wrap(err, `failed to marshal struct (extras)`)
		}
		buf = append(append(buf[:len(buf)-1], ','), extrasBuf[1:]...)
	}
	return buf, nil
}

func (v *xml) UnmarshalJSON(data []byte) error {
	var proxy map[string]json.RawMessage
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	if raw := proxy["$ref"]; len(raw) > 0 {
		if err := json.Unmarshal(raw, &v.reference); err != nil {
			return errors.Wrap(err, `failed to unmarshal $ref`)
		}
		return nil
	}

	if raw := proxy["name"]; len(raw) > 0 {
		if err := json.Unmarshal(raw, &v.name); err != nil {
			return errors.Wrap(err, `failed to unmarshal field name`)
		}
		delete(proxy, "name")
	}

	if raw := proxy["namespace"]; len(raw) > 0 {
		if err := json.Unmarshal(raw, &v.namespace); err != nil {
			return errors.Wrap(err, `failed to unmarshal field namespace`)
		}
		delete(proxy, "namespace")
	}

	if raw := proxy["prefix"]; len(raw) > 0 {
		if err := json.Unmarshal(raw, &v.prefix); err != nil {
			return errors.Wrap(err, `failed to unmarshal field prefix`)
		}
		delete(proxy, "prefix")
	}

	if raw := proxy["attribute"]; len(raw) > 0 {
		if err := json.Unmarshal(raw, &v.attribute); err != nil {
			return errors.Wrap(err, `failed to unmarshal field attribute`)
		}
		delete(proxy, "attribute")
	}

	if raw := proxy["wrapped"]; len(raw) > 0 {
		if err := json.Unmarshal(raw, &v.wrapped); err != nil {
			return errors.Wrap(err, `failed to unmarshal field wrapped`)
		}
		delete(proxy, "wrapped")
	}

	for name, raw := range proxy {
		if strings.HasPrefix(name, `x-`) {
			if v.extras == nil {
				v.extras = Extensions{}
			}
			v.extras[name] = raw
		}
	}
	return nil
}

func (v *xml) Resolve(resolver *Resolver) error {
	if v.IsUnresolved() {

		resolved, err := resolver.Resolve(v.Reference())
		if err != nil {
			return errors.Wrapf(err, `failed to resolve reference %s`, v.Reference())
		}
		asserted, ok := resolved.(*xml)
		if !ok {
			return errors.Wrapf(err, `expected resolved reference to be of type XML, but got %T`, resolved)
		}
		mutator := MutateXML(v)
		mutator.Name(asserted.Name())
		mutator.Namespace(asserted.Namespace())
		mutator.Prefix(asserted.Prefix())
		mutator.Attribute(asserted.Attribute())
		mutator.Wrapped(asserted.Wrapped())
		if err := mutator.Do(); err != nil {
			return errors.Wrap(err, `failed to mutate`)
		}
		v.resolved = true
	}
	return nil
}

func (v *xml) QueryJSON(path string) (ret interface{}, ok bool) {
	path = strings.TrimLeftFunc(path, func(r rune) bool { return r == '#' || r == '/' })
	if path == "" {
		return v, true
	}

	var frag string
	if i := strings.Index(path, "/"); i > -1 {
		frag = path[:i]
		path = path[i+1:]
	} else {
		frag = path
		path = ""
	}

	var target interface{}

	switch frag {
	case "name":
		target = v.name
	case "namespace":
		target = v.namespace
	case "prefix":
		target = v.prefix
	case "attribute":
		target = v.attribute
	case "wrapped":
		target = v.wrapped
	default:
		return nil, false
	}

	if qj, ok := target.(QueryJSONer); ok {
		return qj.QueryJSON(path)
	}
	if path == "" {
		return target, true
	}
	return nil, false
}
