package openapi

// This file was automatically generated by gentypes.go
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// XMLMutator is used to build an instance of XML. The user must
// call `Do()` after providing all the necessary information to
// the new instance of XML with new values
type XMLMutator struct {
	proxy  *xml
	target *xml
}

// Do finalizes the matuation process for XML and returns the result
func (b *XMLMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateXML creates a new mutator object for XML
func MutateXML(v XML) *XMLMutator {
	return &XMLMutator{
		target: v.(*xml),
		proxy:  v.Clone().(*xml),
	}
}

// Name sets the Name field for object XML.
func (m *XMLMutator) Name(v string) *XMLMutator {
	m.proxy.name = v
	return m
}

// Namespace sets the Namespace field for object XML.
func (m *XMLMutator) Namespace(v string) *XMLMutator {
	m.proxy.namespace = v
	return m
}

// Prefix sets the Prefix field for object XML.
func (m *XMLMutator) Prefix(v string) *XMLMutator {
	m.proxy.prefix = v
	return m
}

// Attribute sets the Attribute field for object XML.
func (m *XMLMutator) Attribute(v bool) *XMLMutator {
	m.proxy.attribute = v
	return m
}

// Wrapped sets the Wrapped field for object XML.
func (m *XMLMutator) Wrapped(v bool) *XMLMutator {
	m.proxy.wrapped = v
	return m
}
func (b *XMLMutator) Extension(name string, value interface{}) *XMLMutator {
	if b.proxy.extensions == nil {
		b.proxy.extensions = Extensions{}
	}
	b.proxy.extensions[name] = value
	return b
}
