package openapi

// This file was automatically generated by gentyeps.go on 2018-05-28T16:03:22+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

var _ = log.Printf

// XMLMutator is used to build an instance of XML. The user must
// call `Do()` after providing all the necessary information to
// the new instance of XML with new values
type XMLMutator struct {
	proxy  *xml
	target *xml
}

// Do finalizes the matuation process for XML and returns the result
func (b *XMLMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateXML creates a new mutator object for XML
func MutateXML(v XML) *XMLMutator {
	return &XMLMutator{
		target: v.(*xml),
		proxy:  v.Clone().(*xml),
	}
}

// Name sets the Name field for object XML.
func (b *XMLMutator) Name(v string) *XMLMutator {
	b.proxy.name = v
	return b
}

// Namespace sets the Namespace field for object XML.
func (b *XMLMutator) Namespace(v string) *XMLMutator {
	b.proxy.namespace = v
	return b
}

// Prefix sets the Prefix field for object XML.
func (b *XMLMutator) Prefix(v string) *XMLMutator {
	b.proxy.prefix = v
	return b
}

// Attribute sets the Attribute field for object XML.
func (b *XMLMutator) Attribute(v bool) *XMLMutator {
	b.proxy.attribute = v
	return b
}

// Wrapped sets the Wrapped field for object XML.
func (b *XMLMutator) Wrapped(v bool) *XMLMutator {
	b.proxy.wrapped = v
	return b
}
