package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:06:19+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"github.com/pkg/errors"
)

var _ = errors.Cause

type callbackMarshalProxy struct {
	URLs map[string]PathItem ``
}

type callbackUnmarshalProxy struct {
	URLs map[string]PathItem ``
}

func (v *callback) MarshalJSON() ([]byte, error) {
	var proxy callbackMarshalProxy
	proxy.URLs = v.uRLs
	return json.Marshal(proxy)
}

func (v *callback) UnmarshalJSON(data []byte) error {
	var proxy callbackUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	v.uRLs = proxy.URLs
	return nil
}
