package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:56:43+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *callback) URLs() map[string]PathItem {
	return v.uRLs
}
