package openapi

// This file was automatically generated by genbuilders.go on 2018-05-24T13:02:46+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"github.com/pkg/errors"
	"log"
	"strings"
)

var _ = log.Printf
var _ = errors.Cause

type componentsMarshalProxy struct {
	Reference       string                    `json:"$ref,omitempty"`
	Schemas         map[string]Schema         `json:"schemas,omitempty"`
	Responses       map[string]Response       `json:"responses,omitempty"`
	Parameters      map[string]Parameter      `json:"parameters,omitempty"`
	Examples        map[string]Example        `json:"examples,omitempty"`
	RequestBodies   map[string]RequestBody    `json:"requestBodies,omitempty"`
	Headers         map[string]Header         `json:"headers,omitempty"`
	SecuritySchemes map[string]SecurityScheme `json:"securitySchemes,omitempty"`
	Links           map[string]Link           `json:"links,omitempty"`
	Callbacks       map[string]Callback       `json:"callbacks,omitempty"`
}

type componentsUnmarshalProxy struct {
	Reference       string                     `json:"$ref,omitempty"`
	Schemas         map[string]json.RawMessage `json:"schemas,omitempty"`
	Responses       map[string]json.RawMessage `json:"responses,omitempty"`
	Parameters      map[string]json.RawMessage `json:"parameters,omitempty"`
	Examples        map[string]json.RawMessage `json:"examples,omitempty"`
	RequestBodies   map[string]json.RawMessage `json:"requestBodies,omitempty"`
	Headers         map[string]json.RawMessage `json:"headers,omitempty"`
	SecuritySchemes map[string]json.RawMessage `json:"securitySchemes,omitempty"`
	Links           map[string]json.RawMessage `json:"links,omitempty"`
	Callbacks       map[string]json.RawMessage `json:"callbacks,omitempty"`
}

func (v *components) MarshalJSON() ([]byte, error) {
	var proxy componentsMarshalProxy
	if len(v.reference) > 0 {
		proxy.Reference = v.reference
		return json.Marshal(proxy)
	}
	proxy.Schemas = v.schemas
	proxy.Responses = v.responses
	proxy.Parameters = v.parameters
	proxy.Examples = v.examples
	proxy.RequestBodies = v.requestBodies
	proxy.Headers = v.headers
	proxy.SecuritySchemes = v.securitySchemes
	proxy.Links = v.links
	proxy.Callbacks = v.callbacks
	return json.Marshal(proxy)
}

func (v *components) UnmarshalJSON(data []byte) error {
	var proxy componentsUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	if len(proxy.Reference) > 0 {
		v.reference = proxy.Reference
		return nil
	}

	if len(proxy.Schemas) > 0 {
		m := make(map[string]Schema)
		for key, pv := range proxy.Schemas {
			var decoded schema
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Schemas`, key)
			}
			m[key] = &decoded
		}
		v.schemas = m
	}

	if len(proxy.Responses) > 0 {
		m := make(map[string]Response)
		for key, pv := range proxy.Responses {
			var decoded response
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Responses`, key)
			}
			m[key] = &decoded
		}
		v.responses = m
	}

	if len(proxy.Parameters) > 0 {
		m := make(map[string]Parameter)
		for key, pv := range proxy.Parameters {
			var decoded parameter
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Parameters`, key)
			}
			m[key] = &decoded
		}
		v.parameters = m
	}

	if len(proxy.Examples) > 0 {
		m := make(map[string]Example)
		for key, pv := range proxy.Examples {
			var decoded example
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Examples`, key)
			}
			m[key] = &decoded
		}
		v.examples = m
	}

	if len(proxy.RequestBodies) > 0 {
		m := make(map[string]RequestBody)
		for key, pv := range proxy.RequestBodies {
			var decoded requestBody
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field RequestBodies`, key)
			}
			m[key] = &decoded
		}
		v.requestBodies = m
	}

	if len(proxy.Headers) > 0 {
		m := make(map[string]Header)
		for key, pv := range proxy.Headers {
			var decoded header
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Headers`, key)
			}
			m[key] = &decoded
		}
		v.headers = m
	}

	if len(proxy.SecuritySchemes) > 0 {
		m := make(map[string]SecurityScheme)
		for key, pv := range proxy.SecuritySchemes {
			var decoded securityScheme
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field SecuritySchemes`, key)
			}
			m[key] = &decoded
		}
		v.securitySchemes = m
	}

	if len(proxy.Links) > 0 {
		m := make(map[string]Link)
		for key, pv := range proxy.Links {
			var decoded link
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Links`, key)
			}
			m[key] = &decoded
		}
		v.links = m
	}

	if len(proxy.Callbacks) > 0 {
		m := make(map[string]Callback)
		for key, pv := range proxy.Callbacks {
			var decoded callback
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Callbacks`, key)
			}
			m[key] = &decoded
		}
		v.callbacks = m
	}
	return nil
}

func (v *components) Resolve(resolver *Resolver) error {
	if v.IsUnresolved() {

		resolved, err := resolver.Resolve(v.Reference())
		if err != nil {
			return errors.Wrapf(err, `failed to resolve reference %s`, v.Reference())
		}
		asserted, ok := resolved.(*components)
		if !ok {
			return errors.Wrapf(err, `expected resolved reference to be of type Components, but got %T`, resolved)
		}
		mutator := MutateComponents(v)
		for iter := asserted.Schemas(); iter.Next(); {
			key, item := iter.Item()
			mutator.Schema(key, item)
		}
		for iter := asserted.Responses(); iter.Next(); {
			key, item := iter.Item()
			mutator.Response(key, item)
		}
		for iter := asserted.Parameters(); iter.Next(); {
			key, item := iter.Item()
			mutator.Parameter(key, item)
		}
		for iter := asserted.Examples(); iter.Next(); {
			key, item := iter.Item()
			mutator.Example(key, item)
		}
		for iter := asserted.RequestBodies(); iter.Next(); {
			key, item := iter.Item()
			mutator.RequestBody(key, item)
		}
		for iter := asserted.Headers(); iter.Next(); {
			key, item := iter.Item()
			mutator.Header(key, item)
		}
		for iter := asserted.SecuritySchemes(); iter.Next(); {
			key, item := iter.Item()
			mutator.SecurityScheme(key, item)
		}
		for iter := asserted.Links(); iter.Next(); {
			key, item := iter.Item()
			mutator.Link(key, item)
		}
		for iter := asserted.Callbacks(); iter.Next(); {
			key, item := iter.Item()
			mutator.Callback(key, item)
		}
		if err := mutator.Do(); err != nil {
			return errors.Wrap(err, `failed to mutate`)
		}
		v.resolved = true
	}
	if v.schemas != nil {
		if err := v.schemas.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Schemas`)
		}
	}
	if v.responses != nil {
		if err := v.responses.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Responses`)
		}
	}
	if v.parameters != nil {
		if err := v.parameters.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Parameters`)
		}
	}
	if v.examples != nil {
		if err := v.examples.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Examples`)
		}
	}
	if v.requestBodies != nil {
		if err := v.requestBodies.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve RequestBodies`)
		}
	}
	if v.headers != nil {
		if err := v.headers.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Headers`)
		}
	}
	if v.securitySchemes != nil {
		if err := v.securitySchemes.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve SecuritySchemes`)
		}
	}
	if v.links != nil {
		if err := v.links.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Links`)
		}
	}
	if v.callbacks != nil {
		if err := v.callbacks.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Callbacks`)
		}
	}
	return nil
}

func (v *components) QueryJSON(path string) (ret interface{}, ok bool) {
	path = strings.TrimLeftFunc(path, func(r rune) bool { return r == '#' || r == '/' })
	if path == "" {
		return v, true
	}

	var frag string
	if i := strings.Index(path, "/"); i > -1 {
		frag = path[:i]
		path = path[i+1:]
	} else {
		frag = path
		path = ""
	}

	var target interface{}

	switch frag {
	case "schemas":
		target = v.schemas
	case "responses":
		target = v.responses
	case "parameters":
		target = v.parameters
	case "examples":
		target = v.examples
	case "requestBodies":
		target = v.requestBodies
	case "headers":
		target = v.headers
	case "securitySchemes":
		target = v.securitySchemes
	case "links":
		target = v.links
	case "callbacks":
		target = v.callbacks
	default:
		return nil, false
	}

	if qj, ok := target.(QueryJSONer); ok {
		return qj.QueryJSON(path)
	}
	if path == "" {
		return target, true
	}
	return nil, false
}
