package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:44:15+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *discriminator) PropertyName() string {
	return v.propertyName
}

func (v *discriminator) Mapping() map[string]string {
	return v.mapping
}
