package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:44:15+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

// ExampleBuilder is used to build an instance of Example. The user must
// call `Build()` after providing all the necessary information to
// build an instance of Example
type ExampleBuilder struct {
	target *example
}

// Build finalizes the building process for Example and returns the result
func (b *ExampleBuilder) Build() Example {
	return b.target
}

// NewExample creates a new builder object for Example
func NewExample() *ExampleBuilder {
	return &ExampleBuilder{
		target: &example{},
	}
}

// Description sets the Description field for object Example.
func (b *ExampleBuilder) Description(v string) *ExampleBuilder {
	b.target.description = v
	return b
}

// Value sets the Value field for object Example.
func (b *ExampleBuilder) Value(v interface{}) *ExampleBuilder {
	b.target.value = v
	return b
}

// ExternalValue sets the ExternalValue field for object Example.
func (b *ExampleBuilder) ExternalValue(v string) *ExampleBuilder {
	b.target.externalValue = v
	return b
}
