package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:43:39+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *externalDocumentation) Description() string {
	return v.description
}

func (v *externalDocumentation) URL() string {
	return v.uRL
}
