package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:43:39+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

// ExternalDocumentationMutator is used to build an instance of ExternalDocumentation. The user must
// call `Do()` after providing all the necessary information to
// the new instance of ExternalDocumentation with new values
type ExternalDocumentationMutator struct {
	proxy  *externalDocumentation
	target *externalDocumentation
}

// Get finalizes the matuation process for ExternalDocumentation and returns the result
func (b *ExternalDocumentationMutator) Do() error {
	*b.target = *b.proxy
	return nil
}

// MutateExternalDocumentation creates a new mutator object for ExternalDocumentation
func MutateExternalDocumentation(v ExternalDocumentation) *ExternalDocumentationMutator {
	return &ExternalDocumentationMutator{
		target: v.(*externalDocumentation),
		proxy:  v.Clone().(*externalDocumentation),
	}
}

// Description sets the Description field for object ExternalDocumentation.
func (b *ExternalDocumentationMutator) Description(v string) *ExternalDocumentationMutator {
	b.proxy.description = v
	return b
}

// URL sets the URL field for object ExternalDocumentation.
func (b *ExternalDocumentationMutator) URL(v string) *ExternalDocumentationMutator {
	b.proxy.uRL = v
	return b
}
