package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:57:22+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"github.com/pkg/errors"
)

var _ = errors.Cause

type linkMarshalProxy struct {
	OperationRef string                 `json:"operationRef" yaml:"operationRef"`
	OperationID  string                 `json:"operationId" yaml:"operationId"`
	Parameters   map[string]interface{} `json:"parameters" yaml:"parameters"`
	RequestBody  interface{}            `json:"requestBody" yaml:"requestBody"`
	Description  string                 `json:"description" yaml:"description"`
	Server       *Server                `json:"server" yaml:"server"`
}

type linkUnmarshalProxy struct {
	OperationRef string      `json:"operationRef" yaml:"operationRef"`
	OperationID  string      `json:"operationId" yaml:"operationId"`
	RequestBody  interface{} `json:"requestBody" yaml:"requestBody"`
	Description  string      `json:"description" yaml:"description"`
	Server       *Server     `json:"server" yaml:"server"`
}

func (v *link) MarshalJSON() ([]byte, error) {
	var proxy linkMarshalProxy
	proxy.OperationRef = v.operationRef
	proxy.OperationID = v.operationID
	proxy.Parameters = v.parameters
	proxy.RequestBody = v.requestBody
	proxy.Description = v.description
	proxy.Server = v.server
	return json.Marshal(proxy)
}

func (v *link) UnmarshalJSON(data []byte) error {
	var proxy linkUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	v.operationRef = proxy.OperationRef
	v.operationID = proxy.OperationID
	v.requestBody = proxy.RequestBody
	v.description = proxy.Description
	v.server = proxy.Server
	return nil
}
