package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:44:15+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *mediaType) Schema() Schema {
	return v.schema
}

func (v *mediaType) Example() interface{} {
	return v.example
}

func (v *mediaType) Examples() map[string]Example {
	return v.examples
}

func (v *mediaType) Encoding() map[string]Encoding {
	return v.encoding
}
