package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:43:39+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *openAPI) Version() string {
	return v.version
}

func (v *openAPI) Info() Info {
	return v.info
}

func (v *openAPI) Servers() []Server {
	return v.servers
}

func (v *openAPI) Paths() Paths {
	return v.paths
}

func (v *openAPI) Components() Components {
	return v.components
}

func (v *openAPI) Security() SecurityRequirement {
	return v.security
}

func (v *openAPI) Tags() []Tag {
	return v.tags
}

func (v *openAPI) ExternalDocs() ExternalDocumentation {
	return v.externalDocs
}
