package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:56:43+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

// ReferenceBuilder is used to build an instance of Reference. The user must
// call `Do()` after providing all the necessary information to
// build an instance of Reference
type ReferenceBuilder struct {
	target *reference
}

// Do finalizes the building process for Reference and returns the result
func (b *ReferenceBuilder) Do() Reference {
	return b.target
}

// NewReference creates a new builder object for Reference
func NewReference() *ReferenceBuilder {
	return &ReferenceBuilder{
		target: &reference{},
	}
}

// URL sets the URL field for object Reference.
func (b *ReferenceBuilder) URL(v string) *ReferenceBuilder {
	b.target.uRL = v
	return b
}
