package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:56:43+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"github.com/pkg/errors"
)

var _ = errors.Cause

type referenceMarshalProxy struct {
}

type referenceUnmarshalProxy struct {
}

func (v *reference) MarshalJSON() ([]byte, error) {
	var proxy referenceMarshalProxy
	return json.Marshal(proxy)
}

func (v *reference) UnmarshalJSON(data []byte) error {
	var proxy referenceUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	return nil
}
