package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T21:56:43+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *requestBody) Description() string {
	return v.description
}

func (v *requestBody) Content() map[string]MediaType {
	return v.content
}

func (v *requestBody) Required() bool {
	return v.required
}
