package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:06:19+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"github.com/pkg/errors"
)

var _ = errors.Cause

type responseMarshalProxy struct {
	Description string               `json:"description" builder:"required"`
	Headers     map[string]Header    `json:"headers,omitempty" builder:"-"`
	Content     map[string]MediaType `json:"content,omitempty" builder:"-"`
	Links       map[string]Link      `json:"links,omitempty" builder:"-"`
}

type responseUnmarshalProxy struct {
	Description string               `json:"description" builder:"required"`
	Headers     map[string]Header    `json:"headers,omitempty" builder:"-"`
	Content     map[string]MediaType `json:"content,omitempty" builder:"-"`
	Links       map[string]Link      `json:"links,omitempty" builder:"-"`
}

func (v *response) MarshalJSON() ([]byte, error) {
	var proxy responseMarshalProxy
	proxy.Description = v.description
	proxy.Headers = v.headers
	proxy.Content = v.content
	proxy.Links = v.links
	return json.Marshal(proxy)
}

func (v *response) UnmarshalJSON(data []byte) error {
	var proxy responseUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	v.description = proxy.Description
	v.headers = proxy.Headers
	v.content = proxy.Content
	v.links = proxy.Links
	return nil
}
