package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:06:19+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

// ResponseBuilder is used to build an instance of Response. The user must
// call `Build()` after providing all the necessary information to
// build an instance of Response
type ResponseBuilder struct {
	target *response
}

// Build finalizes the building process for Response and returns the result
func (b *ResponseBuilder) Build() Response {
	return b.target
}

// NewResponse creates a new builder object for Response
func NewResponse(description string) *ResponseBuilder {
	return &ResponseBuilder{
		target: &response{
			description: description,
		},
	}
}
