package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:57:22+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

// ResponsesBuilder is used to build an instance of Responses. The user must
// call `Build()` after providing all the necessary information to
// build an instance of Responses
type ResponsesBuilder struct {
	target *responses
}

// Build finalizes the building process for Responses and returns the result
func (b *ResponsesBuilder) Build() Responses {
	return b.target
}

// NewResponses creates a new builder object for Responses
func NewResponses() *ResponsesBuilder {
	return &ResponsesBuilder{
		target: &responses{},
	}
}

// Default sets the Default field for object Responses.
func (b *ResponsesBuilder) Default(v Response) *ResponsesBuilder {
	b.target.defaultValue = v
	return b
}
