package openapi

// This file was automatically generated by genbuilders.go on 2018-05-24T13:02:46+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"encoding/json"
	"github.com/pkg/errors"
	"log"
	"strings"
)

var _ = log.Printf
var _ = errors.Cause

type schemaMarshalProxy struct {
	Reference        string                `json:"$ref,omitempty"`
	Title            string                `json:"title,omitempty"`
	MultipleOf       float64               `json:"multipleOf,omitempty"`
	Maximum          float64               `json:"maximum,omitempty"`
	ExclusiveMaximum float64               `json:"exclusiveMaximum,omitempty"`
	Minimum          float64               `json:"minimum,omitempty"`
	ExclusiveMinimum float64               `json:"exclusiveMinimum,omitempty"`
	MaxLength        int                   `json:"maxLength,omitempty"`
	MinLength        int                   `json:"minLength,omitempty"`
	Pattern          string                `json:"pattern,omitempty"`
	MaxItems         int                   `json:"maxItems,omitempty"`
	MinItems         int                   `json:"minItems,omitempty"`
	UniqueItems      bool                  `json:"uniqueItems,omitempty"`
	MaxProperties    int                   `json:"maxProperties,omitempty"`
	MinProperties    int                   `json:"minProperties,omitempty"`
	Required         []string              `json:"required,omitempty"`
	Enum             []interface{}         `json:"enum,omitempty"`
	Type             PrimitiveType         `json:"type,omitempty"`
	AllOf            []Schema              `json:"allOf,omitempty"`
	OneOf            []Schema              `json:"oneOf,omitempty"`
	AnyOf            []Schema              `json:"anyOf,omitempty"`
	Not              Schema                `json:"not,omitempty"`
	Items            Schema                `json:"items,omitempty"`
	Properties       map[string]Schema     `json:"properties,omitempty"`
	Format           string                `json:"format,omitempty"`
	Default          interface{}           `json:"default,omitempty"`
	Nullable         bool                  `json:"nullable,omitempty"`
	Discriminator    Discriminator         `json:"discriminator,omitempty"`
	ReadOnly         bool                  `json:"readOnly,omitempty"`
	WriteOnly        bool                  `json:"writeOnly,omitempty"`
	ExternalDocs     ExternalDocumentation `json:"externalDocs,omitempty"`
	Example          interface{}           `json:"example,omitempty"`
	Deprecated       bool                  `json:"deprecated,omitempty"`
}

type schemaUnmarshalProxy struct {
	Reference        string                     `json:"$ref,omitempty"`
	Title            string                     `json:"title,omitempty"`
	MultipleOf       float64                    `json:"multipleOf,omitempty"`
	Maximum          float64                    `json:"maximum,omitempty"`
	ExclusiveMaximum float64                    `json:"exclusiveMaximum,omitempty"`
	Minimum          float64                    `json:"minimum,omitempty"`
	ExclusiveMinimum float64                    `json:"exclusiveMinimum,omitempty"`
	MaxLength        int                        `json:"maxLength,omitempty"`
	MinLength        int                        `json:"minLength,omitempty"`
	Pattern          string                     `json:"pattern,omitempty"`
	MaxItems         int                        `json:"maxItems,omitempty"`
	MinItems         int                        `json:"minItems,omitempty"`
	UniqueItems      bool                       `json:"uniqueItems,omitempty"`
	MaxProperties    int                        `json:"maxProperties,omitempty"`
	MinProperties    int                        `json:"minProperties,omitempty"`
	Type             PrimitiveType              `json:"type,omitempty"`
	AllOf            []json.RawMessage          `json:"allOf,omitempty"`
	OneOf            []json.RawMessage          `json:"oneOf,omitempty"`
	AnyOf            []json.RawMessage          `json:"anyOf,omitempty"`
	Not              json.RawMessage            `json:"not,omitempty"`
	Items            json.RawMessage            `json:"items,omitempty"`
	Properties       map[string]json.RawMessage `json:"properties,omitempty"`
	Format           string                     `json:"format,omitempty"`
	Default          interface{}                `json:"default,omitempty"`
	Nullable         bool                       `json:"nullable,omitempty"`
	Discriminator    json.RawMessage            `json:"discriminator,omitempty"`
	ReadOnly         bool                       `json:"readOnly,omitempty"`
	WriteOnly        bool                       `json:"writeOnly,omitempty"`
	ExternalDocs     json.RawMessage            `json:"externalDocs,omitempty"`
	Example          interface{}                `json:"example,omitempty"`
	Deprecated       bool                       `json:"deprecated,omitempty"`
}

func (v *schema) MarshalJSON() ([]byte, error) {
	var proxy schemaMarshalProxy
	if len(v.reference) > 0 {
		proxy.Reference = v.reference
		return json.Marshal(proxy)
	}
	proxy.Title = v.title
	proxy.MultipleOf = v.multipleOf
	proxy.Maximum = v.maximum
	proxy.ExclusiveMaximum = v.exclusiveMaximum
	proxy.Minimum = v.minimum
	proxy.ExclusiveMinimum = v.exclusiveMinimum
	proxy.MaxLength = v.maxLength
	proxy.MinLength = v.minLength
	proxy.Pattern = v.pattern
	proxy.MaxItems = v.maxItems
	proxy.MinItems = v.minItems
	proxy.UniqueItems = v.uniqueItems
	proxy.MaxProperties = v.maxProperties
	proxy.MinProperties = v.minProperties
	proxy.Required = v.required
	proxy.Enum = v.enum
	proxy.Type = v.typ
	proxy.AllOf = v.allOf
	proxy.OneOf = v.oneOf
	proxy.AnyOf = v.anyOf
	proxy.Not = v.not
	proxy.Items = v.items
	proxy.Properties = v.properties
	proxy.Format = v.format
	proxy.Default = v.defaultValue
	proxy.Nullable = v.nullable
	proxy.Discriminator = v.discriminator
	proxy.ReadOnly = v.readOnly
	proxy.WriteOnly = v.writeOnly
	proxy.ExternalDocs = v.externalDocs
	proxy.Example = v.example
	proxy.Deprecated = v.deprecated
	return json.Marshal(proxy)
}

func (v *schema) UnmarshalJSON(data []byte) error {
	var proxy schemaUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	if len(proxy.Reference) > 0 {
		v.reference = proxy.Reference
		return nil
	}
	v.title = proxy.Title
	v.multipleOf = proxy.MultipleOf
	v.maximum = proxy.Maximum
	v.exclusiveMaximum = proxy.ExclusiveMaximum
	v.minimum = proxy.Minimum
	v.exclusiveMinimum = proxy.ExclusiveMinimum
	v.maxLength = proxy.MaxLength
	v.minLength = proxy.MinLength
	v.pattern = proxy.Pattern
	v.maxItems = proxy.MaxItems
	v.minItems = proxy.MinItems
	v.uniqueItems = proxy.UniqueItems
	v.maxProperties = proxy.MaxProperties
	v.minProperties = proxy.MinProperties
	v.typ = proxy.Type

	if len(proxy.AllOf) > 0 {
		var list []Schema
		for i, pv := range proxy.AllOf {
			var decoded schema
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %d of field AllOf`, i)
			}
			list = append(list, &decoded)
		}
		v.allOf = list
	}

	if len(proxy.OneOf) > 0 {
		var list []Schema
		for i, pv := range proxy.OneOf {
			var decoded schema
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %d of field OneOf`, i)
			}
			list = append(list, &decoded)
		}
		v.oneOf = list
	}

	if len(proxy.AnyOf) > 0 {
		var list []Schema
		for i, pv := range proxy.AnyOf {
			var decoded schema
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %d of field AnyOf`, i)
			}
			list = append(list, &decoded)
		}
		v.anyOf = list
	}

	if len(proxy.Not) > 0 {
		var decoded schema
		if err := json.Unmarshal(proxy.Not, &decoded); err != nil {
			return errors.Wrap(err, `failed to unmarshal field Not`)
		}

		v.not = &decoded
	}

	if len(proxy.Items) > 0 {
		var decoded schema
		if err := json.Unmarshal(proxy.Items, &decoded); err != nil {
			return errors.Wrap(err, `failed to unmarshal field Items`)
		}

		v.items = &decoded
	}

	if len(proxy.Properties) > 0 {
		m := make(map[string]Schema)
		for key, pv := range proxy.Properties {
			var decoded schema
			if err := json.Unmarshal(pv, &decoded); err != nil {
				return errors.Wrapf(err, `failed to unmasrhal element %s of field Properties`, key)
			}
			m[key] = &decoded
		}
		v.properties = m
	}
	v.format = proxy.Format
	v.defaultValue = proxy.Default
	v.nullable = proxy.Nullable

	if len(proxy.Discriminator) > 0 {
		var decoded discriminator
		if err := json.Unmarshal(proxy.Discriminator, &decoded); err != nil {
			return errors.Wrap(err, `failed to unmarshal field Discriminator`)
		}

		v.discriminator = &decoded
	}
	v.readOnly = proxy.ReadOnly
	v.writeOnly = proxy.WriteOnly

	if len(proxy.ExternalDocs) > 0 {
		var decoded externalDocumentation
		if err := json.Unmarshal(proxy.ExternalDocs, &decoded); err != nil {
			return errors.Wrap(err, `failed to unmarshal field ExternalDocs`)
		}

		v.externalDocs = &decoded
	}
	v.example = proxy.Example
	v.deprecated = proxy.Deprecated
	return nil
}

func (v *schema) Resolve(resolver *Resolver) error {
	if v.IsUnresolved() {

		resolved, err := resolver.Resolve(v.Reference())
		if err != nil {
			return errors.Wrapf(err, `failed to resolve reference %s`, v.Reference())
		}
		asserted, ok := resolved.(*schema)
		if !ok {
			return errors.Wrapf(err, `expected resolved reference to be of type Schema, but got %T`, resolved)
		}
		mutator := MutateSchema(v)
		mutator.Name(asserted.Name())
		mutator.Title(asserted.Title())
		mutator.MultipleOf(asserted.MultipleOf())
		mutator.Maximum(asserted.Maximum())
		mutator.ExclusiveMaximum(asserted.ExclusiveMaximum())
		mutator.Minimum(asserted.Minimum())
		mutator.ExclusiveMinimum(asserted.ExclusiveMinimum())
		mutator.MaxLength(asserted.MaxLength())
		mutator.MinLength(asserted.MinLength())
		mutator.Pattern(asserted.Pattern())
		mutator.MaxItems(asserted.MaxItems())
		mutator.MinItems(asserted.MinItems())
		mutator.UniqueItems(asserted.UniqueItems())
		mutator.MaxProperties(asserted.MaxProperties())
		mutator.MinProperties(asserted.MinProperties())
		for iter := asserted.Required(); iter.Next(); {
			item := iter.Item()
			mutator.Required(item)
		}
		for iter := asserted.Enum(); iter.Next(); {
			item := iter.Item()
			mutator.Enum(item)
		}
		mutator.Type(asserted.Type())
		for iter := asserted.AllOf(); iter.Next(); {
			item := iter.Item()
			mutator.AllOf(item)
		}
		for iter := asserted.OneOf(); iter.Next(); {
			item := iter.Item()
			mutator.OneOf(item)
		}
		for iter := asserted.AnyOf(); iter.Next(); {
			item := iter.Item()
			mutator.AnyOf(item)
		}
		mutator.Not(asserted.Not())
		mutator.Items(asserted.Items())
		for iter := asserted.Properties(); iter.Next(); {
			key, item := iter.Item()
			mutator.Property(key, item)
		}
		mutator.Format(asserted.Format())
		mutator.Default(asserted.Default())
		mutator.Nullable(asserted.Nullable())
		mutator.Discriminator(asserted.Discriminator())
		mutator.ReadOnly(asserted.ReadOnly())
		mutator.WriteOnly(asserted.WriteOnly())
		mutator.ExternalDocs(asserted.ExternalDocs())
		mutator.Example(asserted.Example())
		mutator.Deprecated(asserted.Deprecated())
		if err := mutator.Do(); err != nil {
			return errors.Wrap(err, `failed to mutate`)
		}
		v.resolved = true
	}
	if v.required != nil {
		if err := v.required.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Required`)
		}
	}
	if v.enum != nil {
		if err := v.enum.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Enum`)
		}
	}
	if v.allOf != nil {
		if err := v.allOf.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve AllOf`)
		}
	}
	if v.oneOf != nil {
		if err := v.oneOf.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve OneOf`)
		}
	}
	if v.anyOf != nil {
		if err := v.anyOf.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve AnyOf`)
		}
	}
	if v.not != nil {
		if err := v.not.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Not`)
		}
	}
	if v.items != nil {
		if err := v.items.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Items`)
		}
	}
	if v.properties != nil {
		if err := v.properties.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Properties`)
		}
	}
	if v.discriminator != nil {
		if err := v.discriminator.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Discriminator`)
		}
	}
	if v.externalDocs != nil {
		if err := v.externalDocs.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve ExternalDocs`)
		}
	}
	return nil
}

func (v *schema) QueryJSON(path string) (ret interface{}, ok bool) {
	path = strings.TrimLeftFunc(path, func(r rune) bool { return r == '#' || r == '/' })
	if path == "" {
		return v, true
	}

	var frag string
	if i := strings.Index(path, "/"); i > -1 {
		frag = path[:i]
		path = path[i+1:]
	} else {
		frag = path
		path = ""
	}

	var target interface{}

	switch frag {
	case "title":
		target = v.title
	case "multipleOf":
		target = v.multipleOf
	case "maximum":
		target = v.maximum
	case "exclusiveMaximum":
		target = v.exclusiveMaximum
	case "minimum":
		target = v.minimum
	case "exclusiveMinimum":
		target = v.exclusiveMinimum
	case "maxLength":
		target = v.maxLength
	case "minLength":
		target = v.minLength
	case "pattern":
		target = v.pattern
	case "maxItems":
		target = v.maxItems
	case "minItems":
		target = v.minItems
	case "uniqueItems":
		target = v.uniqueItems
	case "maxProperties":
		target = v.maxProperties
	case "minProperties":
		target = v.minProperties
	case "required":
		target = v.required
	case "enum":
		target = v.enum
	case "type":
		target = v.typ
	case "allOf":
		target = v.allOf
	case "oneOf":
		target = v.oneOf
	case "anyOf":
		target = v.anyOf
	case "not":
		target = v.not
	case "items":
		target = v.items
	case "properties":
		target = v.properties
	case "format":
		target = v.format
	case "default":
		target = v.defaultValue
	case "nullable":
		target = v.nullable
	case "discriminator":
		target = v.discriminator
	case "readOnly":
		target = v.readOnly
	case "writeOnly":
		target = v.writeOnly
	case "externalDocs":
		target = v.externalDocs
	case "example":
		target = v.example
	case "deprecated":
		target = v.deprecated
	default:
		return nil, false
	}

	if qj, ok := target.(QueryJSONer); ok {
		return qj.QueryJSON(path)
	}
	if path == "" {
		return target, true
	}
	return nil, false
}
