package openapi

// This file was automatically generated by gentyeps.go on 2018-05-29T07:35:18+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *securityRequirement) Schemes() *StringListMapIterator {
	var items []interface{}
	for key, item := range v.schemes {
		items = append(items, &mapIteratorItem{key: key, item: item})
	}
	var iter StringListMapIterator
	iter.list.items = items
	return &iter
}

func (v *securityRequirement) Reference() string {
	return v.reference
}

func (v *securityRequirement) IsUnresolved() bool {
	return v.reference != "" && !v.resolved
}
