package openapi

// This file was automatically generated by genbuilders.go on 2018-05-20T20:06:19+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

func (v *securityScheme) Type() string {
	return v.typ
}

func (v *securityScheme) Description() string {
	return v.description
}

func (v *securityScheme) Name() string {
	return v.name
}

func (v *securityScheme) In() string {
	return v.in
}

func (v *securityScheme) Scheme() string {
	return v.scheme
}

func (v *securityScheme) BearerFormat() string {
	return v.bearerFormat
}

func (v *securityScheme) Flows() OAuthFlows {
	return v.flows
}

func (v *securityScheme) OpenIDConnectURL() string {
	return v.openIDConnectURL
}
