package openapi

// This file was automatically generated by genbuilders.go on 2018-05-24T11:15:54+09:00
// DO NOT EDIT MANUALLY. All changes will be lost

import (
	"log"
)

import (
	"encoding/json"
	"github.com/pkg/errors"
	"strings"
)

var _ = errors.Cause

type serverVariableMarshalProxy struct {
	Reference   string   `json:"$ref,omitempty"`
	Enum        []string `json:"enum"`
	Default     string   `json:"default"`
	Description string   `json:"description"`
}

type serverVariableUnmarshalProxy struct {
	Reference   string `json:"$ref,omitempty"`
	Default     string `json:"default"`
	Description string `json:"description"`
}

func (v *serverVariable) MarshalJSON() ([]byte, error) {
	var proxy serverVariableMarshalProxy
	if len(v.reference) > 0 {
		proxy.Reference = v.reference
		return json.Marshal(proxy)
	}
	proxy.Enum = v.enum
	proxy.Default = v.defaultValue
	proxy.Description = v.description
	return json.Marshal(proxy)
}

func (v *serverVariable) UnmarshalJSON(data []byte) error {
	var proxy serverVariableUnmarshalProxy
	if err := json.Unmarshal(data, &proxy); err != nil {
		return err
	}
	if len(proxy.Reference) > 0 {
		v.reference = proxy.Reference
		return nil
	}
	v.defaultValue = proxy.Default
	v.description = proxy.Description
	return nil
}

func (v *serverVariable) Resolve(resolver *Resolver) error {
	log.Printf(`serverVariable.Resolve`)
	if v.IsReference() {
		resolved, err := resolver.Resolve(v.Reference())
		if err != nil {
			return errors.Wrapf(err, `failed to resolve reference %s`, v.Reference())
		}
		asserted, ok := resolved.(*serverVariable)
		if !ok {
			return errors.Wrapf(err, `expected resolved reference to be of type ServerVariable, but got %T`, resolved)
		}
		mutator := MutateServerVariable(v)
		for iter := asserted.Enum(); iter.Next(); {
			item := iter.Item()
			mutator.Enum(item)
		}
		mutator.Default(asserted.Default())
		mutator.Description(asserted.Description())
		return errors.Wrap(mutator.Do(), `failed to mutate`)
	}
	if v.enum != nil {
		if err := v.enum.Resolve(resolver); err != nil {
			return errors.Wrap(err, `failed to resolve Enum`)
		}
	}
	return nil
}

func (v *serverVariable) QueryJSON(path string) (ret interface{}, ok bool) {
	path = strings.TrimLeftFunc(path, func(r rune) bool { return r == '#' || r == '/' })
	if path == "" {
		return v, true
	}

	var frag string
	if i := strings.Index(path, "/"); i > -1 {
		frag = path[:i]
		path = path[i+1:]
	} else {
		frag = path
		path = ""
	}

	var target interface{}

	switch frag {
	case "enum":
		target = v.enum
	case "default":
		target = v.defaultValue
	case "description":
		target = v.description
	default:
		return nil, false
	}

	if qj, ok := target.(QueryJSONer); ok {
		return qj.QueryJSON(path)
	}
	if path == "" {
		return target, true
	}
	return nil, false
}
